name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn dist
    - run: yarn test:node
    - run: yarn test:browser
      env:
        CI: true
