name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: macos-latest

        strategy:
            matrix:
                node-version: [v20, v22]
        env:
            CI: true
            LINT: ${{ matrix.node-version == 'v22' && true || false }}
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: corepack enable
            - run: yarn install
            - run: yarn build
            - run: yarn test:node
            - run: yarn test:browser
            - run: yarn lint:ci
              if: ${{ env.LINT == 'true' }}
